# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

linuxGoEnv1_14: &linuxGoEnv1_14
  docker:
    - image: golang:1.14
  environment:
    GOROOT: /usr/local/go
  working_directory: /go/src/github.com/olimpias/gvm

linuxGoEnv1_10: &linuxGoEnv1_10
    docker:
      - image: golang:1.10
    environment:
      GOROOT: /usr/local/go
    working_directory: /go/src/github.com/olimpias/gvm

jobs:
    unit-tests:
      <<: *linuxGoEnv1_14
      steps:
        - checkout
        # specify any bash command here prefixed with `run: `
        - run: go get -v -t -d ./...
        - run: go test -v ./...

    integration-test-linux:
      <<: *linuxGoEnv1_10
      steps:
        - checkout
        - run: go get ./...
        - run: go build -o gvm ./cmd
        - run: ./gvm dl 1.14.4
        - run: ./gvm use 1.14.4
        - run: var=$(go version)
        - run: '[[ $var == "go version go1.14.3 darwin/amd64" ]] && exit 0 || exit 1'

workflows:
  version: 2
  all:
    jobs:
      - unit-tests
      - integration-test-linux

